In [58]:
import numpy as np
from numpy import genfromtxt

# do podziału na zbiór testowy i trenigowy
from sklearn.model_selection import train_test_split

# do skalowania danych
from sklearn.preprocessing import MinMaxScaler

# do budowania podstawowej sieci neuronowej
from  keras.models import Sequential
from keras.layers import Dense

# do ewaluacji modelu
from sklearn.metrics import confusion_matrix, classification_report

In [24]:
# zera w ostatniej kolumnie oznaczaja, że fałszywe dane
# jedynki oznaczają prawdziwe dane
# w tm przypadku są to etykiety lub klasy
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [25]:
data.shape

(1372, 5)

In [26]:
# podział danych na etykiety (labels) i cechy (features)

In [27]:
labels = data[:,4]

In [28]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [29]:
features = data[:,0:4]

In [30]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [31]:
# podzaił na zbiór testowy i treningowy:

In [32]:
X = features
y = labels

In [33]:
train_test_split # shift-tab

<function sklearn.model_selection._split.train_test_split(*arrays, **options)>

In [34]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [38]:
# skalowanie danych:

In [39]:
scaler_object = MinMaxScaler()

In [40]:
scaler_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [41]:
scaled_X_train = scaler_object.transform(X_train)

In [43]:
scaled_X_test = scaler_object.transform(X_test)

In [47]:
# budowanie modelu:

In [48]:
model = Sequential()

In [51]:
# dodawnie warstw
model.add(Dense(4,input_dim=4,activation='relu'))

model.add(Dense(8,activation='relu'))

model.add(Dense(1,activation='sigmoid'))

In [52]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [53]:
# trenowanie modelu:
model.fit(scaled_X_train,y_train,epochs=50,verbose=2)

Epoch 1/50
 - 1s - loss: 0.6903 - acc: 0.5495
Epoch 2/50
 - 0s - loss: 0.6885 - acc: 0.5495
Epoch 3/50
 - 0s - loss: 0.6882 - acc: 0.5495
Epoch 4/50
 - 0s - loss: 0.6884 - acc: 0.5495
Epoch 5/50
 - 0s - loss: 0.6878 - acc: 0.5495
Epoch 6/50
 - 0s - loss: 0.6873 - acc: 0.5495
Epoch 7/50
 - 0s - loss: 0.6862 - acc: 0.5495
Epoch 8/50
 - 0s - loss: 0.6845 - acc: 0.5495
Epoch 9/50
 - 0s - loss: 0.6821 - acc: 0.5495
Epoch 10/50
 - 0s - loss: 0.6791 - acc: 0.5495
Epoch 11/50
 - 0s - loss: 0.6750 - acc: 0.5495
Epoch 12/50
 - 0s - loss: 0.6685 - acc: 0.5495
Epoch 13/50
 - 0s - loss: 0.6572 - acc: 0.5495
Epoch 14/50
 - 0s - loss: 0.6404 - acc: 0.5495
Epoch 15/50
 - 0s - loss: 0.6112 - acc: 0.5495
Epoch 16/50
 - 0s - loss: 0.5678 - acc: 0.7661
Epoch 17/50
 - 0s - loss: 0.5182 - acc: 0.8390
Epoch 18/50
 - 0s - loss: 0.4687 - acc: 0.8683
Epoch 19/50
 - 0s - loss: 0.4231 - acc: 0.9032
Epoch 20/50
 - 0s - loss: 0.3879 - acc: 0.9108
Epoch 21/50
 - 0s - loss: 0.3571 - acc: 0.9293
Epoch 22/50
 - 0s - lo

In [55]:
# testowanie modelu na testowym zbiorze danych:

In [59]:
# predykcja testowych danych:
predictions = model.predict_classes(scaled_X_test)

In [60]:
# ewaluacja modelu:
model.metrics_names

['loss', 'acc']

In [61]:
confusion_matrix(y_test,predictions)

array([[253,   4],
       [  2, 194]], dtype=int64)

In [62]:
print(classification_report(y_test,predictions))

             precision    recall  f1-score   support

        0.0       0.99      0.98      0.99       257
        1.0       0.98      0.99      0.98       196

avg / total       0.99      0.99      0.99       453



In [63]:
# zapisywanie modelu:
model.save('mysupermodel.h5')

In [64]:
# wczytywanie modelu:
from keras.models import load_model

In [65]:
new_model = load_model('mysupermodel.h5')